
[packages.cython]
version = "0.29.21"

[packages.numpy]
version = "1.19.4"
build_pip_requirements = ["Cython==0.29.21"]
cross_pip_requirements = ["robotpy-openblas-dev"]
install_requirements = ["robotpy-openblas"]

[packages.numpy.environment]
F90 = "arm-frc2020-linux-gnueabi-gfortran"

[packages.ptvsd]
version = "4.3.2"

[packages.pydevd]
version = "2.0.0"

[packages.pyinstrument_cext]
version = "0.2.2"

# TODO
# [packages.scipy]
# version = "1.5.3"
