
[packages.cython]
version = "0.29.21"

# TODO
# [packages.numpy]
# version = "1.19.2"
# build_requirements = ["robotpy-openblas-dev"]
# install_requirements = ["robotpy-openblas"]

[packages.ptvsd]
version = "4.3.2"

[packages.pydevd]
version = "2.0.0"

[packages.pyinstrument_cext]
version = "0.2.2"

# TODO
# [packages.scipy]
# version = "1.5.3"
